version: 2.0

references:
  executor_config: &executor_config
    docker:
      - image: circleci/node:10.16
    working_directory: ~/app

jobs:
  setup:
    <<: *executor_config
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1.0-dependencies-{{ checksum "package-lock.json" }}
          - v1.0-dependencies-

      - run: npm install
      - run: npm install -g @alethio/cms-plugin-tool

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: .
          paths: .

  build:
    <<: *executor_config
    steps:
      - attach_workspace:
          at: .

      - run: npm run build
      - run: >
          acp install
          "@alethio/explorer-plugin-eth-common@1.0.2"
          "@alethio/explorer-plugin-eth-lite@1.0.3"
          "@alethio/explorer-plugin-eth-ibft2@1.0.1"
          "@alethio/explorer-plugin-3box@1.0.1"

      - persist_to_workspace:
          root: .
          paths: .

  deploy:
    <<: *executor_config
    steps:
      - attach_workspace:
          at: .
      - run: sudo npm install surge --global
      - run: cp config.default.json dist/config.json
      # - run: echo ${CONFIG_JSON} > dist/config.json
      - run: cp dist/index.html dist/200.html
      - run: surge dist/ ${CIRCLE_BRANCH}.lite-explorer.surge.sh

      #- run: sudo npm install surge-teardown-branches --global
      #- run: |
      #      mkdir -p ~/.ssh/
      #      echo -e "Host github.com\n\tStrictHostKeyChecking no\n\tUserKnownHostsFile /dev/null\n" > ~/.ssh/config
      #      chmod 600 ~/.ssh/config
      #      ssh-keyscan -Ht rsa github.com >> ~/.ssh/known_hosts
      #- run: surge-teardown-branches lite-explorer.surge.sh
      #- run: git ls-remote --heads

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - setup
      - build:
          requires:
            - setup
      - deploy:
          requires:
            - build
