apiVersion: v1
kind: Service
metadata:
  labels:
    app: ethereum-lite-explorer-service
  name: ethereum-lite-explorer-service
spec:
  ports:
  - name: "25000"
    port: 25000
    targetPort: 80
  selector:
    app: ethereum-lite-explorer

